Repository elastic/cloud-sdk-go, pull requests merged in 2020-09, with the labels that each got.

#200 api: Add missing Create response on traffic rule assoc
  Makefile
  api/apidocs.json
  api/version/2.6.1.md
  go.sum
  pkg/api/version.go
  pkg/client/deployments_traffic_filter/create_traffic_filter_ruleset_association_responses.go
  pkg/client/deployments_traffic_filter/deployments_traffic_filter_client.go
Labels: Team:Delivery, bug

#201 stackapi: Update semver import path
  go.sum
  pkg/api/stackapi/delete.go
  pkg/api/stackapi/get.go
Labels: dependencies

#204 trafficfilterapi: Add CRUD and association APIs
  pkg/api/deploymentapi/trafficfilterapi/create.go
  pkg/api/deploymentapi/trafficfilterapi/create_association.go
  pkg/api/deploymentapi/trafficfilterapi/create_association_test.go
  pkg/api/deploymentapi/trafficfilterapi/create_test.go
  pkg/api/deploymentapi/trafficfilterapi/delete.go
  pkg/api/deploymentapi/trafficfilterapi/delete_association.go
  pkg/api/deploymentapi/trafficfilterapi/delete_association_test.go
  pkg/api/deploymentapi/trafficfilterapi/delete_test.go
  pkg/api/deploymentapi/trafficfilterapi/get.go
  pkg/api/deploymentapi/trafficfilterapi/get_test.go
  pkg/api/deploymentapi/trafficfilterapi/list.go
  pkg/api/deploymentapi/trafficfilterapi/list_test.go
  pkg/api/deploymentapi/trafficfilterapi/update.go
  pkg/api/deploymentapi/trafficfilterapi/update_test.go
Labels: Team:Delivery, enhancement

#205 allocatorapi: Add Size parameter to ListParams
  pkg/api/platformapi/allocatorapi/list.go
  pkg/api/platformapi/allocatorapi/list_test.go
Labels: Team:Delivery

#207 allocatorapi: Add ListParams field comments
  pkg/api/platformapi/allocatorapi/list.go
Labels: Team:Delivery, documentation

#206 depresourceapi: Add Reset elasticsearch password
  pkg/api/deploymentapi/depresourceapi/reset_es_password.go
  pkg/api/deploymentapi/depresourceapi/reset_es_password_test.go
Labels: Team:Delivery, enhancement

#209 deploymentapi: Add ConvertLegacyPlans to Get
  pkg/api/deploymentapi/get.go
  pkg/api/deploymentapi/get_test.go
Labels: enhancement

#216 sync/pool: Add FailFast parameter, stopping on err
  .golangci.yml
  pkg/sync/pool/pool.go
  pkg/sync/pool/pool_examples_test.go
  pkg/sync/pool/pool_params.go
  pkg/sync/pool/pool_test.go
Labels: Team:Delivery, enhancement

#217 actions: Add scheduled api-validation job
  .github/workflows/apivalidation.yml
  CONTRIBUTING.md
  build/Makefile.apivalidation
  build/Makefile.deps
  build/Makefile.swagger
  build/apivalidation/apivalidation_test.go
Labels: breaking change, enhancement

#218 apivalidation: Set workflow to Go 1.14
  .github/workflows/apivalidation.yml
Labels: bug

#220 api: Add CustomTransport unifying RoundTripper(s)
  .golangci.yml
  go.sum
  pkg/api/api.go
  pkg/api/config.go
  pkg/api/debug.go
  pkg/api/debug_test.go
  pkg/api/deprecated_transport_debug.go
  pkg/api/deprecated_transport_debug_test.go
  pkg/api/deprecated_transport_errcatch.go
  pkg/api/deprecated_transport_errcatch_test.go
  pkg/api/deprecated_transport_user_agent.go
  pkg/api/deprecated_transport_user_agent_test.go
  pkg/api/http_transport.go
  pkg/api/http_transport_test.go
  pkg/api/transport_custom.go
  pkg/api/transport_custom_test.go
Labels: Team:Delivery, enhancement
