Repository elastic/cloud-sdk-go, pull requests merged in 2020-05, with the labels that each got.

#102 misc: update issue template labels
  .github/ISSUE_TEMPLATE/BUG_REPORT.md
  .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
  .github/ISSUE_TEMPLATE/GENERIC_QUESTION.md
Labels: Team:Delivery

#104 plan: Use local multierror.Prefixed as multierror
  pkg/plan/planutil/track.go
  pkg/plan/planutil/track_test.go
  pkg/plan/stream.go
  pkg/plan/track_change_params.go
  pkg/plan/track_change_test.go
Labels: Team:Delivery

#107 ec: Seed random so randoms actually are random
  pkg/util/ec/rand.go
Labels: Team:Delivery, bug

#108 ec: Add missing rand unit tests
  pkg/util/ec/rand.go
  pkg/util/ec/rand_test.go
Labels: Team:Delivery

#112 api: Fix transport error on UserAgentTransport
  pkg/api/http_transport.go
  pkg/api/http_transport_test.go
Labels: Team:Delivery, bug

#113 deploymentapi: Allow overrides on Update operation
  pkg/api/deploymentapi/create.go
  pkg/api/deploymentapi/update.go
Labels: Team:Delivery, enhancement

#114 api: Use http.Transport.Clone() for new transports
  go.mod
  go.sum
  pkg/api/http_transport.go
Labels: Team:Delivery, framework

#116 mock: Add ability to assert received *http.Request
  go.mod
  pkg/api/mock/client.go
  pkg/api/mock/client_test.go
  pkg/api/mock/request.go
  pkg/api/mock/request_test.go
  pkg/api/mock/response.go
Labels: Team:Delivery, enhancement

#118 api: transport now handles raw metadata producer
  go.sum
  pkg/api/client_runtime.go
  pkg/api/client_runtime_test.go
Labels: Team:Delivery, bug
