Repository elastic/cloud-sdk-go, pull requests merged in 2020-04, with the labels that each got.

#87 deps: revert multierror to 1.0.0
  go.mod
  go.sum
Labels: area:delivery, framework, loe:small

#89 cmdutil: Add DecodeFlags to reduce parsing code
  go.mod
  pkg/util/cmdutil/flag.go
  pkg/util/cmdutil/flag_test.go
Labels: area:delivery, enhancement, loe:small

#98 release: Update version to 1.0.0-beta3 and create changelog
  Makefile
  notes/v1.0.0-beta3.md
Labels: area:delivery
