Repository elastic/cloud-sdk-go, pull requests merged in 2020-01, with the labels that each got.

#35 Fix godoc link
  README.md
Labels: area:tooling, bug, documentation

#32 Add versioned API commands as a markdown doc
  Makefile
  README.md
  api/version/2.4.3.md
  build/Makefile.swagger
  cmd/generator/cloudspec/spec_commands.go
  cmd/generator/cloudspec/spec_commands_test.go
  cmd/generator/main.go
  cmd/generator/main_test.go
  go.sum
  pkg/api/version.go
Labels: enhancement, loe:medium

#40 misc: add release and changelog make targets
  Makefile
  build/Makefile.build
  notes/EXAMPLE.md
  scripts/changelog.tpl.md
  scripts/generate-changelog.sh
Labels: area:tooling, enhancement, loe:medium

#41 test: Fix flaky 'TestPoolAdd/Add_succeeds' test
  go.mod
  pkg/sync/pool/pool_test.go
Labels: area:tooling, bug, loe:small

#43 move string slice from soteria
  pkg/util/slice/string.go
  pkg/util/slice/string_test.go
Labels: area:tooling

#46 api: Add CloudClientRuntime client.Runtime wrapper
  pkg/api/api.go
  pkg/api/client_runtime.go
  pkg/api/client_runtime_test.go
Labels: area:tooling, bug, loe:medium

#48 bump golang-ci linter version to 1.22.2
  .golangci.yml
  build/Makefile.deps
Labels: area:tooling

#47 add the soteria logging wrarppers,utils and assertions
  pkg/logging/assert.go
  pkg/logging/ecs.go
  pkg/logging/ecs_test.go
  pkg/logging/standardoutput/standard_output_logger.go
  pkg/logging/standardoutput/standard_output_logger_test.go
Labels: area:tooling, loe:small

#49 api: /deployment/{id}/notes should use region path
  pkg/api/client_runtime.go
  pkg/api/client_runtime_test.go
Labels: area:tooling, bug, loe:small

#50 improve logging names and package structure
  pkg/logging/logger/elasticsearch/es_logger.go
  pkg/logging/logger/standardoutput/dispatcher.go
  pkg/logging/logger/standardoutput/dispatcher_test.go
  pkg/logging/logger/standardoutput/logger.go
  pkg/logging/logger/standardoutput/logger_test.go
  pkg/logging/logging.go
  pkg/logging/logging_test.go
  pkg/logging/standardoutput/standard_output_logger.go
  pkg/logging/standardoutput/standard_output_logger_test.go
Labels: area:tooling

#54 util: copy cmdutil package files that are not specific to ecctl
  go.mod
  go.sum
  pkg/util/cmdutil/confirmation.go
  pkg/util/cmdutil/confirmation_test.go
  pkg/util/cmdutil/error.go
  pkg/util/cmdutil/flag.go
  pkg/util/cmdutil/flag_test.go
  pkg/util/cmdutil/fs.go
  pkg/util/cmdutil/fs_test.go
  pkg/util/cmdutil/input.go
  pkg/util/cmdutil/input_test.go
  pkg/util/cmdutil/parse.go
  pkg/util/cmdutil/path.go
  pkg/util/cmdutil/path_test.go
  pkg/util/cmdutil/prerun.go
  pkg/util/cmdutil/prerun_test.go
Labels: area:tooling, enhancement, loe:small

#55 release: changelog and version tag for 1.0.0-bc14
  Makefile
  developer_docs/RELEASE.md
  notes/v1.0.0-bc14.md
Labels: area:tooling, loe:small
