Repository elastic/cloud-sdk-go, pull requests merged in 2020-03, with the labels that each got.

#65 plan: Fix bug where last step error was missed
  pkg/plan/track.go
  pkg/plan/track_test.go
Labels: area:tooling, bug, loe:small

#68 deps: Bump golangci-lint to v1.23.8
  build/Makefile.deps
Labels: area:tooling, loe:small

#77 api: Add custom User-Agent transport
  pkg/api/api.go
  pkg/api/config.go
  pkg/api/http_transport.go
  pkg/api/transport_user_agent.go
  pkg/api/transport_user_agent_test.go
Labels: area:tooling, enhancement, loe:medium

#78 release: Add notes for v1.0.0-beta2
  build/Makefile.build
  notes/v1.0.0-beta2.md
Labels: area:tooling, documentation, loe:small

#66 plan: Add change tracker backed by Deployments API
  pkg/api/mock/response.go
  pkg/api/mock/response_test.go
  pkg/plan/deprecated_poller.go
  pkg/plan/deprecated_poller_test.go
  pkg/plan/deprecated_track.go
  pkg/plan/deprecated_track_test.go
  pkg/plan/doc.go
  pkg/plan/lookup_query.go
  pkg/plan/lookup_query_test.go
  pkg/plan/mock/generator.go
  pkg/plan/mock/generator_test.go
  pkg/plan/mock/helper.go
  pkg/plan/mock/helper_test.go
  pkg/plan/planutil/doc.go
  pkg/plan/planutil/track.go
  pkg/plan/planutil/track_test.go
  pkg/plan/planutil/wait.go
  pkg/plan/planutil/wait_test.go
  pkg/plan/stream.go
  pkg/plan/stream_format.go
  pkg/plan/stream_test.go
  pkg/plan/track_change.go
  pkg/plan/track_change_params.go
  pkg/plan/track_change_test.go
  pkg/plan/track_response.go
  pkg/plan/track_response_builder.go
  pkg/plan/track_step.go
  pkg/plan/track_step_test.go
  pkg/util/ec/rand.go
  pkg/util/ec/rand_test.go
Labels: area:tooling, loe:large

#80 api: Modify transport to handle Proxied responses
  pkg/api/transport_errcatch.go
  pkg/api/transport_errcatch_test.go
Labels: area:tooling, bug, loe:small

#81 multierror: Add package with Prefixed error type
  pkg/multierror/doc.go
  pkg/multierror/examples_test.go
  pkg/multierror/prefixed.go
  pkg/multierror/prefixed_example_test.go
  pkg/multierror/prefixed_test.go
Labels: area:tooling, enhancement, loe:medium

#82 misc: update codeowners
  .github/CODEOWNERS
Labels: area:delivery, loe:small
