Repository elastic/cloud-sdk-go, pull requests merged in 2020-07, with the labels that each got.

#162 configurationtemplateapi: Add Format field
  pkg/api/deploymentapi/depresourceapi/apm.go
  pkg/api/deploymentapi/depresourceapi/appsearch.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch.go
  pkg/api/deploymentapi/depresourceapi/kibana.go
  pkg/api/platformapi/configurationtemplateapi/delete_test.go
  pkg/api/platformapi/configurationtemplateapi/get.go
  pkg/api/platformapi/configurationtemplateapi/get_test.go
  pkg/api/platformapi/configurationtemplateapi/list.go
  pkg/api/platformapi/configurationtemplateapi/list_test.go
  pkg/api/platformapi/configurationtemplateapi/pull.go
  pkg/api/platformapi/configurationtemplateapi/pull_test.go
Labels: breaking change, enhancement

#163 test: introduce CLI/tests for validating API spec against live API and run on 'make swagger'
  Makefile
  build/Makefile.apivalidation
  build/Makefile.deps
  build/Makefile.swagger
  build/apivalidation/apivalidation_test.go
  internal/cmd/apivalidator/main.go
  internal/cmd/apivalidator/requests/run.go
  internal/cmd/apivalidator/requests/run_test.go
  internal/cmd/apivalidator/requests/test/apidocs-valid.json
  internal/cmd/apivalidator/requests/test/corrupted.json
  internal/pkg/apivalidator/request.go
  internal/pkg/apivalidator/request_test.go
  internal/pkg/internalutil/command.go
Labels: enhancement, framework

#166 apivalidator: Add empty body to PATCH requests
  internal/pkg/apivalidator/request.go
Labels: bug

#169 apivalidator: Modifies the request builder to take into account required query
  build/Makefile.apivalidation
  internal/pkg/apivalidator/request.go
Labels: Team:Delivery, bug

#170 deploymentapi: Support for Enterprise Search and refactor
  pkg/api/deploymentapi/apm/request.go
  pkg/api/deploymentapi/apm/request_test.go
  pkg/api/deploymentapi/depresourceapi/delete_stateless_test.go
  pkg/api/deploymentapi/depresourceapi/restore_test.go
  pkg/api/deploymentapi/depresourceapi/shutdown_test.go
  pkg/api/deploymentapi/deputil/kinds.go
  pkg/api/deploymentapi/get.go
  pkg/api/deploymentapi/get_resource.go
  pkg/api/deploymentapi/get_resource_test.go
  pkg/api/deploymentapi/get_test.go
  pkg/api/deploymentapi/kibana/request.go
  pkg/api/deploymentapi/kibana/request_test.go
  pkg/api/deploymentapi/override_settings.go
  pkg/api/deploymentapi/override_settings_test.go
Labels: enhancement, framework

#171 deptemplateapi: Add all CRUD APIs
  pkg/api/deploymentapi/deptemplateapi/create.go
  pkg/api/deploymentapi/deptemplateapi/create_test.go
  pkg/api/deploymentapi/deptemplateapi/delete.go
  pkg/api/deploymentapi/deptemplateapi/delete_test.go
  pkg/api/deploymentapi/deptemplateapi/get.go
  pkg/api/deploymentapi/deptemplateapi/get_test.go
  pkg/api/deploymentapi/deptemplateapi/list.go
  pkg/api/deploymentapi/deptemplateapi/list_test.go
  pkg/api/deploymentapi/deptemplateapi/testdata/create.json
  pkg/api/deploymentapi/deptemplateapi/testdata/get.json
  pkg/api/deploymentapi/deptemplateapi/testdata/list.json
  pkg/api/deploymentapi/deptemplateapi/testdata/update.json
  pkg/api/deploymentapi/deptemplateapi/update.go
  pkg/api/deploymentapi/deptemplateapi/update_test.go
Labels: Team:Delivery, enhancement

#174 depresourceapi: Update resource APIs to use new deployment template endpoint
  pkg/api/deploymentapi/depresourceapi/apm.go
  pkg/api/deploymentapi/depresourceapi/apm_test.go
  pkg/api/deploymentapi/depresourceapi/appsearch.go
  pkg/api/deploymentapi/depresourceapi/appsearch_test.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_parser_test.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_test.go
  pkg/api/deploymentapi/depresourceapi/enterprise_search.go
  pkg/api/deploymentapi/depresourceapi/enterprise_search_test.go
  pkg/api/deploymentapi/depresourceapi/kibana.go
  pkg/api/deploymentapi/depresourceapi/kibana_test.go
  pkg/api/deploymentapi/depresourceapi/new_payload.go
  pkg/api/deploymentapi/depresourceapi/new_payload_test.go
  pkg/api/deploymentapi/depresourceapi/new_stateless.go
Labels: Team:Delivery, breaking change, framework

#173 docs: Improve README and CONTRIBUTING docs with updated information
  CONTRIBUTING.md
  README.md
Labels: documentation

#177 docs: Add cloud-sdk-go specific styleguide
  CONTRIBUTING.md
  developer_docs/STYLEGUIDE.md
Labels: Team:Delivery, documentation

#178 deploymentapi: Support List and filter templates
  pkg/api/deploymentapi/depresourceapi/apm_test.go
  pkg/api/deploymentapi/depresourceapi/appsearch_test.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_parser.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_parser_test.go
  pkg/api/deploymentapi/depresourceapi/enterprise_search_test.go
  pkg/api/deploymentapi/depresourceapi/kibana_test.go
  pkg/api/deploymentapi/depresourceapi/new_payload.go
  pkg/api/deploymentapi/depresourceapi/new_payload_test.go
  pkg/api/deploymentapi/depresourceapi/new_stateless.go
  pkg/api/deploymentapi/deptemplateapi/get.go
  pkg/api/deploymentapi/deptemplateapi/get_test.go
Labels: Team:Delivery

#181 deploymentapi: Add NewUpdateRequest function
  pkg/api/deploymentapi/testdata/apm_get.json
  pkg/api/deploymentapi/testdata/apm_update.json
  pkg/api/deploymentapi/testdata/appsearch_get.json
  pkg/api/deploymentapi/testdata/appsearch_update.json
  pkg/api/deploymentapi/testdata/enterprise_search_get.json
  pkg/api/deploymentapi/testdata/enterprise_search_update.json
  pkg/api/deploymentapi/update_payload.go
  pkg/api/deploymentapi/update_payload_test.go
Labels: Team:Delivery, enhancement

#182 depresourceapi: Change the 'Name' field in ElasticsearchTopologyElement for 'NodeType'
  pkg/api/deploymentapi/depresourceapi/elasticsearch_parser_test.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_test.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_topology.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_topology_test.go
Labels: breaking change

#183 deploymentsize: Fixes a bug in ParseGb()
  pkg/api/deploymentapi/deploymentsize/sizes.go
  pkg/api/deploymentapi/deploymentsize/sizes_test.go
Labels: bug

#184 release: Add v1.0.0 changelog
  Makefile
  README.md
  notes/beta/v1.0.0-bc14.md
  notes/beta/v1.0.0-beta1.md
  notes/beta/v1.0.0-beta2.md
  notes/beta/v1.0.0-beta3.md
  notes/v1.0.0.md
Labels: Team:Delivery, documentation
