Repository elastic/cloud-sdk-go, pull requests merged in 2020-12, with the labels that each got.

#257 adds a few StringSlice receiver methods
  pkg/util/slice/string.go
  pkg/util/slice/string_test.go
Labels: Team:Delivery

#249 deploymentapi: Add observability settings to NewUpdateRequest
  pkg/api/deploymentapi/testdata/observability_get.json
  pkg/api/deploymentapi/testdata/observability_update.json
  pkg/api/deploymentapi/update_payload.go
  pkg/api/deploymentapi/update_payload_test.go
Labels: bug

#261 adds a function to create an int pointer from an int
  pkg/util/ec/types.go
  pkg/util/ec/types_test.go
Labels: Team:Delivery

#264 deploymentapi: Fix update payload
  go.sum
  pkg/api/deploymentapi/testdata/observability_get.json
  pkg/api/deploymentapi/update_payload.go
  pkg/api/deploymentapi/update_payload_test.go
Labels: bug

#265 stack: Fix version sorting algorithm
  pkg/api/stackapi/list.go
  pkg/api/stackapi/list_test.go
Labels: Team:Delivery, bug
