Repository elastic/cloud-sdk-go, pull requests merged in 2020-06, with the labels that each got.

#120 api: NewMock now uses NewAPI as the constructor
  pkg/api/deploymentapi/resync_test.go
  pkg/api/mock.go
  pkg/auth/testutil.go
Labels: enhancement

#122 mock: Add url Query assertion
  pkg/api/mock/request.go
  pkg/api/mock/request_test.go
Labels: enhancement

#111 deploymentsize: change Parse to only accept g
  pkg/api/deploymentapi/deploymentsize/sizes.go
  pkg/api/deploymentapi/deploymentsize/sizes_test.go
Labels: Team:Delivery

#123 api: Add RedactAuth bool option to VerboseSettings
  go.sum
  pkg/api/config.go
  pkg/api/debug.go
  pkg/api/debug_test.go
  pkg/api/http_transport.go
Labels: enhancement

#124 api: Add WithRegion context for region bound calls
  pkg/api/client_runtime.go
  pkg/api/client_runtime_test.go
  pkg/api/config.go
  pkg/api/context_region.go
  pkg/api/doc.go
Labels: breaking change, enhancement

#131 api: Export default mock headers and host
  pkg/api/mock.go
Labels: framework

#134 stackapi: Add Region field and WithRegion ctx
  pkg/api/platformapi/stackapi/delete.go
  pkg/api/platformapi/stackapi/delete_test.go
  pkg/api/platformapi/stackapi/get.go
  pkg/api/platformapi/stackapi/get_test.go
  pkg/api/platformapi/stackapi/list.go
  pkg/api/platformapi/stackapi/list_test.go
  pkg/api/platformapi/stackapi/stack_test.go
  pkg/api/platformapi/stackapi/upload.go
  pkg/api/platformapi/stackapi/upload_test.go
Labels: Team:Delivery, breaking change

#135 constructorapi: Add Region param and WithRegion
  pkg/api/platformapi/constructorapi/constructor_test.go
  pkg/api/platformapi/constructorapi/get.go
  pkg/api/platformapi/constructorapi/get_test.go
  pkg/api/platformapi/constructorapi/list.go
  pkg/api/platformapi/constructorapi/list_test.go
  pkg/api/platformapi/constructorapi/maintenance.go
  pkg/api/platformapi/constructorapi/maintenance_test.go
  pkg/api/platformapi/constructorapi/resync.go
  pkg/api/platformapi/constructorapi/resync_test.go
Labels: breaking change

#136 snaprepoapi: Add Region field and WithRegion ctx
  pkg/api/platformapi/snaprepoapi/delete.go
  pkg/api/platformapi/snaprepoapi/delete_test.go
  pkg/api/platformapi/snaprepoapi/get.go
  pkg/api/platformapi/snaprepoapi/get_test.go
  pkg/api/platformapi/snaprepoapi/list.go
  pkg/api/platformapi/snaprepoapi/list_test.go
  pkg/api/platformapi/snaprepoapi/repository_params.go
  pkg/api/platformapi/snaprepoapi/repository_test.go
  pkg/api/platformapi/snaprepoapi/set.go
  pkg/api/platformapi/snaprepoapi/set_test.go
Labels: breaking change

#137 enrollmenttokenapi:Add Region param and WithRegion
  pkg/api/platformapi/enrollmenttokenapi/create.go
  pkg/api/platformapi/enrollmenttokenapi/create_test.go
  pkg/api/platformapi/enrollmenttokenapi/delete.go
  pkg/api/platformapi/enrollmenttokenapi/delete_test.go
  pkg/api/platformapi/enrollmenttokenapi/list.go
  pkg/api/platformapi/enrollmenttokenapi/list_test.go
  pkg/api/platformapi/enrollmenttokenapi/token_test.go
Labels: breaking change

#138 runnerapi: Add Region field and WithRegion ctx
  pkg/api/platformapi/runnerapi/list.go
  pkg/api/platformapi/runnerapi/list_test.go
  pkg/api/platformapi/runnerapi/params.go
  pkg/api/platformapi/runnerapi/params_test.go
  pkg/api/platformapi/runnerapi/resync.go
  pkg/api/platformapi/runnerapi/resync_test.go
  pkg/api/platformapi/runnerapi/search.go
  pkg/api/platformapi/runnerapi/search_test.go
  pkg/api/platformapi/runnerapi/show.go
  pkg/api/platformapi/runnerapi/show_test.go
Labels: Team:Delivery, breaking change

#139 roleapi: Add Region field and WithRegion ctx
  pkg/api/mock/response.go
  pkg/api/mock/response_test.go
  pkg/api/platformapi/roleapi/add_blessing.go
  pkg/api/platformapi/roleapi/add_blessing_test.go
  pkg/api/platformapi/roleapi/create.go
  pkg/api/platformapi/roleapi/create_test.go
  pkg/api/platformapi/roleapi/delete.go
  pkg/api/platformapi/roleapi/delete_test.go
  pkg/api/platformapi/roleapi/list.go
  pkg/api/platformapi/roleapi/list_test.go
  pkg/api/platformapi/roleapi/set_blessing.go
  pkg/api/platformapi/roleapi/set_blessing_test.go
  pkg/api/platformapi/roleapi/show.go
  pkg/api/platformapi/roleapi/show_test.go
  pkg/api/platformapi/roleapi/update.go
  pkg/api/platformapi/roleapi/update_test.go
Labels: Team:Delivery, breaking change

#146 template: Add region parameter to all APIs
  pkg/api/platformapi/configurationtemplateapi/create.go
  pkg/api/platformapi/configurationtemplateapi/create_test.go
  pkg/api/platformapi/configurationtemplateapi/delete.go
  pkg/api/platformapi/configurationtemplateapi/delete_test.go
  pkg/api/platformapi/configurationtemplateapi/get.go
  pkg/api/platformapi/configurationtemplateapi/get_test.go
  pkg/api/platformapi/configurationtemplateapi/list.go
  pkg/api/platformapi/configurationtemplateapi/list_test.go
  pkg/api/platformapi/configurationtemplateapi/params.go
  pkg/api/platformapi/configurationtemplateapi/pull.go
  pkg/api/platformapi/configurationtemplateapi/pull_test.go
  pkg/api/platformapi/configurationtemplateapi/template.go
  pkg/api/platformapi/configurationtemplateapi/template_test.go
  pkg/api/platformapi/configurationtemplateapi/update.go
  pkg/api/platformapi/configurationtemplateapi/update_test.go
Labels: breaking change

#144 filteredgroupapi: Add Region field and WithRegion ctx
  pkg/api/platformapi/proxyapi/filteredgroupapi/create.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/create_test.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/delete.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/delete_test.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/filtered_group.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/filtered_group_test.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/get.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/get_test.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/list.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/list_test.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/update.go
  pkg/api/platformapi/proxyapi/filteredgroupapi/update_test.go
Labels: Team:Delivery

#148 platformapi: Add region parameter to all APIs
  pkg/api/platformapi/info.go
  pkg/api/platformapi/info_test.go
Labels: Team:Delivery, breaking change

#149 proxyapi: Add Region field and WithRegion ctx
  pkg/api/platformapi/proxyapi/get.go
  pkg/api/platformapi/proxyapi/get_test.go
  pkg/api/platformapi/proxyapi/list.go
  pkg/api/platformapi/proxyapi/list_test.go
  pkg/api/platformapi/proxyapi/proxy_test.go
Labels: Team:Delivery, breaking change

#151 allocator vacate: Add enterprise search support
  pkg/api/platformapi/allocatorapi/vacate.go
  pkg/api/platformapi/allocatorapi/vacate_full_test.go
  pkg/api/platformapi/allocatorapi/vacate_params.go
  pkg/api/platformapi/allocatorapi/vacate_params_test.go
  pkg/api/platformapi/allocatorapi/vacate_responses_test.go
  pkg/api/platformapi/allocatorapi/vacate_test.go
  pkg/plan/mock/generator.go
  pkg/plan/mock/generator_test.go
  pkg/plan/track_change_test.go
  pkg/plan/track_response.go
  pkg/plan/track_response_builder.go
  pkg/util/kinds.go
Labels: Team:Delivery, enhancement

#156 api: Add global route mappings and require region
  pkg/api/api_test.go
  pkg/api/client_runtime.go
  pkg/api/client_runtime_test.go
  pkg/api/config.go
  pkg/api/context_region.go
  pkg/api/deploymentapi/depresourceapi/apm.go
  pkg/api/deploymentapi/depresourceapi/appsearch.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch.go
  pkg/api/deploymentapi/depresourceapi/elasticsearch_parser.go
  pkg/api/deploymentapi/depresourceapi/kibana.go
  pkg/api/deploymentapi/depresourceapi/stack_latest.go
  pkg/api/deploymentapi/depresourceapi/stack_latest_test.go
  pkg/api/deploymentapi/noteapi/add.go
  pkg/api/deploymentapi/noteapi/add_test.go
  pkg/api/deploymentapi/noteapi/list.go
  pkg/api/deploymentapi/noteapi/list_test.go
  pkg/api/deploymentapi/noteapi/params.go
  pkg/api/deploymentapi/noteapi/show.go
  pkg/api/deploymentapi/noteapi/show_test.go
  pkg/api/deploymentapi/noteapi/update.go
  pkg/api/deploymentapi/noteapi/update_test.go
  pkg/api/platformapi/allocatorapi/search.go
  pkg/api/platformapi/allocatorapi/search_test.go
  pkg/plan/deprecated_poller.go
  pkg/plan/deprecated_poller_test.go
  pkg/plan/deprecated_track.go
  pkg/plan/deprecated_track_test.go
  pkg/plan/stream_test.go
  pkg/plan/track_step_test.go
Labels: Team:Delivery, bug

#157 api: Add mock.RoundTripper to transport workflow
  pkg/api/http_transport.go
  pkg/api/http_transport_test.go
Labels: Team:Delivery, framework

#158 stackapi: Move stackapi up one level
  pkg/api/deploymentapi/depresourceapi/stack_latest.go
  pkg/api/stackapi/delete.go
  pkg/api/stackapi/delete_test.go
  pkg/api/stackapi/get.go
  pkg/api/stackapi/get_test.go
  pkg/api/stackapi/list.go
  pkg/api/stackapi/list_test.go
  pkg/api/stackapi/upload.go
  pkg/api/stackapi/upload_test.go
Labels: breaking change, enhancement

#155 userapi: Moves user APIs from ecctl
  pkg/api/userapi/authapi/adminapi/deletekey.go
  pkg/api/userapi/authapi/adminapi/deletekey_test.go
  pkg/api/userapi/authapi/adminapi/doc.go
  pkg/api/userapi/authapi/adminapi/getkey.go
  pkg/api/userapi/authapi/adminapi/getkey_test.go
  pkg/api/userapi/authapi/adminapi/listkeys.go
  pkg/api/userapi/authapi/adminapi/listkeys_test.go
  pkg/api/userapi/authapi/createkey.go
  pkg/api/userapi/authapi/createkey_test.go
  pkg/api/userapi/authapi/deletekey.go
  pkg/api/userapi/authapi/deletekey_test.go
  pkg/api/userapi/authapi/doc.go
  pkg/api/userapi/authapi/getkey.go
  pkg/api/userapi/authapi/getkey_test.go
  pkg/api/userapi/authapi/listkeys.go
  pkg/api/userapi/authapi/listkeys_test.go
  pkg/api/userapi/authapi/reauthenticate.go
  pkg/api/userapi/create.go
  pkg/api/userapi/create_test.go
  pkg/api/userapi/delete.go
  pkg/api/userapi/delete_test.go
  pkg/api/userapi/doc.go
  pkg/api/userapi/enable.go
  pkg/api/userapi/enable_test.go
  pkg/api/userapi/get.go
  pkg/api/userapi/get_test.go
  pkg/api/userapi/list.go
  pkg/api/userapi/list_test.go
  pkg/api/userapi/roles.go
  pkg/api/userapi/roles_test.go
  pkg/api/userapi/update.go
  pkg/api/userapi/update_test.go
  pkg/util/email/email.go
  pkg/util/email/email_test.go
Labels: enhancement
