Repository elastic/cloud-sdk-go, pull requests merged in 2021-12, with the labels that each got.

#371 Changelogs for 1.7.0
  .changelog/1.7.0/364.yml
Labels: Team:Delivery

#369 Avoid escaping JSON string payload for set-deployment-resource-raw-metadata
  pkg/api/client_runtime.go
  pkg/api/client_runtime_test.go
Labels: bug

#367 Add insecure attribute on cluster meta
  pkg/models/cluster_metadata_info.go
Labels: enhancement, Team:Delivery, tooling-requests
