Repository elastic/cloud-sdk-go, pull requests merged in 2021-01, with the labels that each got.

#267 deploymentapi: Parse memory_per_node as well
  pkg/api/deploymentapi/testdata/logging_metrics_legacy_kibana_get.json
  pkg/api/deploymentapi/testdata/logging_metrics_legacy_kibana_update.json
  pkg/api/deploymentapi/testdata/observability_get.json
  pkg/api/deploymentapi/testdata/observability_update.json
  pkg/api/deploymentapi/update_payload.go
  pkg/api/deploymentapi/update_payload_test.go
Labels: Team:Delivery, bug

#269 deploymentapi: Add new CRUD APIs for extensions
  pkg/api/deploymentapi/extensionapi/create.go
  pkg/api/deploymentapi/extensionapi/create_test.go
  pkg/api/deploymentapi/extensionapi/delete.go
  pkg/api/deploymentapi/extensionapi/delete_test.go
  pkg/api/deploymentapi/extensionapi/get.go
  pkg/api/deploymentapi/extensionapi/get_test.go
  pkg/api/deploymentapi/extensionapi/list.go
  pkg/api/deploymentapi/extensionapi/list_test.go
  pkg/api/deploymentapi/extensionapi/update.go
  pkg/api/deploymentapi/extensionapi/update_test.go
Labels: enhancement

#270 doc: Fixes broken readme example
  README.md
Labels: documentation

#277 multierror: Make concurrently safe and sort errors
  pkg/api/platformapi/allocatorapi/search_test.go
  pkg/multierror/prefixed.go
  pkg/multierror/prefixed_test.go
Labels: enhancement
