Repository elastic/cloud-sdk-go, pull requests merged in 2021-03, with the labels that each got.

#292 plan tracker: Update failure modes
  pkg/api/platformapi/allocatorapi/vacate_full_test.go
  pkg/plan/track_step.go
  pkg/plan/track_step_test.go
Labels: Team:Delivery, bug

#293 chore: Update Go and dependency versions
  .github/workflows/apivalidation.yml
  .github/workflows/go.yml
  .golangci.yml
  build/Makefile.deps
  go.mod
  go.sum
Labels: dependencies

#295 plan tracker: fix missed plan error on fast plan completion
  go.mod
  go.sum
  pkg/api/platformapi/allocatorapi/vacate_full_test.go
  pkg/plan/track_change.go
  pkg/plan/track_change_test.go
Labels: Team:Delivery, bug

#297 Add Go reference badge to readme
  README.md
Labels: Team:Delivery, documentation

#298 [extensionapi] Adds a new upload API
  pkg/api/deploymentapi/extensionapi/upload.go
  pkg/api/deploymentapi/extensionapi/upload_test.go
Labels: enhancement

#299 extansionapi: Add validation on required fields
  pkg/api/deploymentapi/extensionapi/create.go
  pkg/api/deploymentapi/extensionapi/create_test.go
  pkg/api/deploymentapi/extensionapi/update.go
  pkg/api/deploymentapi/extensionapi/update_test.go
Labels: bug

#304 trafficfilterapi: Fix bug in validation
  pkg/api/deploymentapi/trafficfilterapi/create_association.go
  pkg/api/deploymentapi/trafficfilterapi/create_association_test.go
  pkg/api/deploymentapi/trafficfilterapi/delete_association.go
  pkg/api/deploymentapi/trafficfilterapi/delete_association_test.go
Labels: bug

#302 deploymentapi: Add OverrideCreateOrUpdateRequest
  pkg/api/deploymentapi/create.go
  pkg/api/deploymentapi/override_settings.go
  pkg/api/deploymentapi/override_settings_test.go
  pkg/api/deploymentapi/update.go
Labels: Team:Delivery, enhancement

#310 release: Add v1.3.0 changelog
  go.sum
  notes/v1.3.0.md
  scripts/changelog.tpl.md
Labels: documentation

#312 Bump versions after releasing 1.3 for ECE 2.9.0
  Makefile
Labels: Team:Delivery

#313 extensionapi: Functionality to build an update request form get
  pkg/api/deploymentapi/extensionapi/update.go
  pkg/api/deploymentapi/extensionapi/update_payload.go
  pkg/api/deploymentapi/extensionapi/update_payload_test.go
Labels: enhancement

#316 go: Remove golint and fix issues
  .golangci.yml
  build/Makefile.deps
  build/Makefile.dev
  pkg/api/platformapi/allocatorapi/testutil_test.go
  pkg/api/userapi/roles.go
  pkg/api/userapi/roles_test.go
  pkg/auth/testutil_test.go
Labels: tech-debt

#315 tracker: Add plan step details
  pkg/api/platformapi/allocatorapi/vacate_full_test.go
  pkg/plan/track_change_test.go
  pkg/plan/track_response.go
  pkg/plan/track_response_builder.go
  pkg/plan/track_step.go
  pkg/plan/track_step_test.go
Labels: enhancement

#317 trafficfilterapi: create an update request from get
  pkg/api/deploymentapi/trafficfilterapi/update_payload.go
  pkg/api/deploymentapi/trafficfilterapi/update_payload_test.go
Labels: enhancement

#318 test: Update test to latest apidocs changes
  pkg/api/deploymentapi/trafficfilterapi/update_payload_test.go
Labels: bug
